---
- name: update sshd_config
  blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Match User git    # Apply the AuthorizedKeysCommands to the git user only
        AuthorizedKeysCommand /opt/gitlab/embedded/service/gitlab-shell/bin/gitlab-shell-authorized-keys-check git %u %k
        AuthorizedKeysCommandUser git
      Match all    # End match, settings apply to all users again
  notify: restart sshd