---
- name: restart gitlab gitlab-runsvdir.service
  service:
    name: gitlab-runsvdir
    state: restarted
    enabled: yes
  when: ansible_os_family == 'Suse'
- name: restart gitlab
  command: gitlab-ctl reconfigure
  register: gitlab_restart
  failed_when: gitlab_restart_handler_failed_when | bool
- name: restart sshd
  service:
    name: sshd
    state: restarted
    enabled: yes